name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    name: build  # build+test on various versions of OCaml, on linux
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        container:
          - ghcr.io/c-cube/c-cube-common/ci-5.0:latest
          - ghcr.io/c-cube/c-cube-common/ci-5.4:latest

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v6
      - run: apt update # && apt-get install libjemalloc-dev -y
      - run: opam pin .#HEAD -y -n
      - run: opam install -t . --deps-only
      - run: opam exec -- dune build @all --ignore-promoted-rules
      - run: opam exec -- dune runtest -p benchpress
